name: "Authenticate to Environment with Lock"
description: 'Authenticate to a Salesforce environment with exclusive locking and automatic unlock'
author: "flxbl-io"

branding:
  icon: "anchor"
  color: "green"

inputs:
  environment:
    description: "Name of the environment to lock and authenticate"
    required: true
  repository:
    description: "Repository name (format: owner/repo)"
    required: false
    default: ${{ github.repository }}
  duration:
    description: "Lock duration in minutes"
    required: false
    default: "60"
  reason:
    description: "Reason for locking the environment (e.g., 'PR #123 validation')"
    required: false
    default: ""
  sfp-server-url:
    description: "URL to the SFP Server instance (e.g., https://your-org.flxbl.io)"
    required: true
  sfp-server-token:
    description: "Token for SFP Server authentication"
    required: true
  wait-timeout:
    description: "Maximum time to wait for lock acquisition in minutes (0 = wait indefinitely)"
    required: false
    default: "0"
  auto-unlock:
    description: "Automatically unlock the environment when the workflow completes"
    required: false
    default: "true"

outputs:
  alias:
    description: "Alias used for the authenticated org (same as environment name)"
  ticket-id:
    description: "Lock ticket ID (used for manual unlock if auto-unlock is disabled)"
  instance-url:
    description: "Instance URL of the authenticated org"
  access-token:
    description: "Access token for the authenticated org"
  username:
    description: "Salesforce username of the authenticated org"
  is-active:
    description: "Whether the lock was acquired"
  auth-method:
    description: "Authentication method used (sfp-server)"

runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/cleanup.js"
  post-if: "always()"
